Repository Anakael/Treasury-Department, pull requests merged in 2019-07, with the labels that each got.

#4 Feature/create empty mvc
  .gitignore
  TreasuryDepartment.sln
  TreasuryDepartment/Controllers/ValuesController.cs
  TreasuryDepartment/Program.cs
  TreasuryDepartment/Properties/launchSettings.json
  TreasuryDepartment/Startup.cs
  TreasuryDepartment/TreasuryDepartment.csproj
  TreasuryDepartment/appsettings.Development.json
  TreasuryDepartment/appsettings.json
Labels: Core, enhancement

#8 Add EF Core Application model
  .gitignore
  TreasuryDepartment/Models/Balance.cs
  TreasuryDepartment/Models/Deal.cs
  TreasuryDepartment/Models/Group.cs
  TreasuryDepartment/Models/Invite.cs
  TreasuryDepartment/Models/TreasuryDepartmentContext.cs
  TreasuryDepartment/Models/User.cs
  TreasuryDepartment/Models/UserGroup.cs
  TreasuryDepartment/Startup.cs
  TreasuryDepartment/appsettings.json
Labels: Core, documentation, enhancement, good first issue

#11 Documentation/data scheme
  .vscode/launch.json
  .vscode/tasks.json
  DataScheme.png
Labels: Core, documentation, good first issue
